services:
  agents:
    image: '${DOCKER_IMAGE_AGENTS?Variable not set}:${TAG-latest}'
    build:
      context: .
      dockerfile: ./apps/agents/Dockerfile
    restart: always
    networks:
      - avli-network
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=${ENVIRONMENT?Variable not set}
      - AGENTS_CORS_ORIGINS=${AGENTS_CORS_ORIGINS?Variable not set}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestor:
    image: '${DOCKER_IMAGE_INGESTOR?Variable not set}:${TAG-latest}'
    build:
      context: .
      dockerfile: ./apps/ingestor/Dockerfile
    restart: always
    networks:
      - avli-network
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=${ENVIRONMENT?Variable not set}
      - INGESTOR_CORS_ORIGINS=${INGESTOR_CORS_ORIGINS?Variable not set}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  qdrant:
    image: docker.io/qdrant/qdrant:v1.19.0
    container_name: qdrant-vector-db
    restart: unless-stopped
    volumes:
      - ./qdrant-vector-db/qdrant_data:/qdrant/storage
    ports:
      - ${QDRANT_REST_PORT?Variable not set}:6333
    networks:
      - avli-network
    env_file:
      - .env.prod
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:6333"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s

  redis:
    image: docker.io/redis:8.8.2-alpine3.23
    container_name: redis-db
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_REST_PORT?Variable not set}:6379
    networks:
      - avli-network
    env_file:
      - .env.prod
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD?Variable not set} --appendonly yes
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:6379"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  qdrant_storage:
    driver: local
  redis_data:
    driver: local

networks:
  avli-network:
    driver: bridge
