catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vitest: 4.1.11
  vite-plus: 0.3.2
  "@vitest/browser-playwright": 4.1.11
  oxlint: 1.83.0
  oxfmt: 0.68.0

overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
