services:
  asset-intel-service:
    container_name: asset-intel-service
    build:
      context: .
      dockerfile: ../services/asset-intel-service/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    ports:
      - ${AIS_REST_PORT?Variable not set}:8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT?Variable not set}
      - AIS_CORS_ORIGINS=${AIS_CORS_ORIGINS?Variable not set}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/v1/utils/health-check/",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - avli-apps-network
    env_file:
      - .env
    depends_on:
      pgvector:
        condition: service_healthy

  celery:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ../celery.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    networks:
      - avli-apps-network
    env_file:
      - .env
    depends_on:
      - redis

  pgvector:
    container_name: pgvector
    image: docker.io/pgvector/pgvector:pg18-trixie
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT?Variable not set}:5432
    environment:
      - POSTGRES_DB=${DATABASE_DB_NAME}
      - POSTGRES_USER=${DATABASE_DB_USER}
      - POSTGRES_PASSWORD=${DATABASE_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_DB_USER} -d ${DATABASE_DB_NAME}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - avli-apps-network
    env_file:
      - .env

  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey:8.1.6-alpine
    restart: always
    ports:
      - ${CACHE_PORT?Variable not set}:6379
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 5s
    networks:
      - avli-apps-network
    env_file:
      - .env

  qdrant:
    image: docker.io/qdrant/qdrant:v1.19.1-unprivileged
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - ${KNOWLEDGE_BASE_PORT?Variable not set}:6333
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:6333"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    networks:
      - avli-apps-network
    env_file:
      - .env

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  valkey-data:
    driver: local
  postgres-data:
    driver: local
  qdrant_data:
    driver: local

networks:
  avli-apps-network:
    driver: bridge
