services:
  # Monitoring Dashboard
  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana:13.0.8-slim
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - ${GRAFANA_PORT?Variable not set}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_SECURITY_ADMIN_PASSWORD}
    networks:
      - avli-obs-network
    env_file:
      - .env

  # Metric Aggregation System
  prometheus:
    container_name: prometheus
    image: docker.io/prom/prometheus:v3.13.3
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_PORT?Variable not set}:9091
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - avli-obs-network
    env_file:
      - .env

  # Container Metric Collector
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - ${CADVISOR_PORT?Variable not set}:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - avli-obs-network
    env_file:
      - .env

  # Log Aggregation System
  loki:
    container_name: loki
    image: docker.io/grafana/loki:3.7.7
    restart: unless-stopped
    ports:
      - ${LOKI_PORT?Variable not set}:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - avli-obs-network
    env_file:
      - .env

  # Log Aggregation Collector
  alloy:
    container_name: alloy
    image: docker.io/grafana/alloy:v1.19.2
    restart: unless-stopped
    ports:
      - ${ALLOY_PORT?Variable not set}:12345
    volumes:
      - ./docker/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    networks:
      - avli-obs-network
    env_file:
      - .env
    depends_on:
      - loki

volumes:
  grafana-data:
    driver: local
  alloy-data:
    driver: local

networks:
  avli-obs-network:
    driver: bridge
