services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ../apps/web/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    ports:
      - ${WEB_PORT?Variable not set}:5173
    env_file:
      - .env
    networks:
      - avli-apps-network

  caddy:
    container_name: web
    image: docker.io/caddy:latest
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    ports:
      - ${REVERSE_PROXY_HTTP_PORT?Variable not set}:80
      - ${REVERSE_PROXY_HTTPS_PORT?Variable not set}:443
    depends_on:
      - web
    env_file:
      - .env
    networks:
      - avli-apps-network

volumes:
  caddy-data:

networks:
  avli-apps-network:
    driver: bridge
