services:
  asset-intel:
    container_name: asset-intel
    build:
      context: .
      dockerfile: ../apps/asset-intel-service/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    ports:
      - ${AIS_REST_PORT?Variable not set}:8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT?Variable not set}
      - AIS_CORS_ORIGINS=${AIS_CORS_ORIGINS?Variable not set}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/v1/utils/health-check/",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - avli-network
    env_file:
      - .env
    depends_on:
      pgvector:
        condition: service_healthy

  celery:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ../celery.Dockerfile
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    networks:
      - avli-network
    env_file:
      - .env
    depends_on:
      - redis

  pgvector:
    container_name: pgvector
    image: docker.io/pgvector/pgvector:pg18-trixie
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT?Variable not set}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - avli-network
    env_file:
      - .env

  redis:
    container_name: redis
    image: docker.io/redis:8.10.1-alpine3.23
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT?Variable not set}:6379
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD?Variable not set} --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    networks:
      - avli-network
    env_file:
      - .env

  redis-insight:
    container_name: redis-insight
    image: docker.io/redis/redisinsight:3.8.0
    restart: unless-stopped
    volumes:
      - redis_insight:/data
    ports:
      - ${REDIS_INSIGHT_PORT?Variable not set}:5540
    networks:
      - avli-network
    env_file:
      - .env

  qdrant:
    image: docker.io/qdrant/qdrant:v1.19.1-unprivileged
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - ${QDRANT_REST_PORT?Variable not set}:6333
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:6333"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    networks:
      - avli-network
    env_file:
      - .env

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  postgres-data:
    driver: local
  redis_data:
    driver: local
  redis_insight:
    driver: local
  qdrant_data:
    driver: local

networks:
  avli-network:
    driver: bridge
