global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "agents"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["app:8000"]

  - job_name: "ingestor"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["app:8001"]
